val scalaJSVersion = Option(System.getenv("SCALAJS_VERSION")).getOrElse("1.1.1")

addSbtPlugin("ch.epfl.scala"             % "sbt-scalafix"             % "0.9.15-3")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"             % "2.4.0")
addSbtPlugin("org.scoverage"             % "sbt-scoverage"            % "1.6.1")
addSbtPlugin("org.jmotor.sbt"            % "sbt-dependency-updates"   % "1.2.2")
addSbtPlugin("org.portable-scala"        % "sbt-scalajs-crossproject" % "1.0.0")
addSbtPlugin("org.scala-js"              % "sbt-scalajs"              % scalaJSVersion)
addSbtPlugin("com.sksamuel.scapegoat"    %% "sbt-scapegoat"           % "1.1.0")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"             % "0.1.13")
addSbtPlugin("org.xerial.sbt"            % "sbt-sonatype"             % "3.9.4")
addSbtPlugin("com.jsuereth"              % "sbt-pgp"                  % "2.0.1")
addSbtPlugin("com.github.gseitz"         % "sbt-release"              % "1.0.13")
